# Generated by Django 2.2 on 2019-04-23 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barcodelookup', '0004_auto_20190409_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=14)),
                ('website', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
                ('website', models.CharField(default='', max_length=100)),
                ('review_stars', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=-1)),
                ('priority', models.CharField(choices=[('h', 'high'), ('m', 'medium'), ('l', 'low')], default='m', max_length=2)),
                ('description', models.TextField(default='')),
                ('image_url', models.TextField(default='')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='barcodelookup.Product')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.ShopProfile')),
            ],
        ),
    ]
