# Generated by Django 2.2 on 2019-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
