# Generated by Django 2.2 on 2019-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20190424_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
