# Generated by Django 2.2 on 2019-04-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_shopprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.UserProfile'),
        ),
    ]
