# Generated by Django 2.2 on 2019-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20190424_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(default='not available'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image_url',
            field=models.TextField(default='https://i.ibb.co/dj1qb0D/product-image-not-found.gif'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='website',
            field=models.CharField(default='not available', max_length=100),
        ),
    ]
