# Generated by Django 2.2 on 2019-04-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20190424_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barcodelookup.Product'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.ShopProfile'),
        ),
    ]
