# Generated by Django 2.2 on 2019-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20190424_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image_url',
            field=models.TextField(default='/media/images/product-image-not-found.gif'),
        ),
    ]
