# Generated by Django 2.2 on 2019-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20190424_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='address',
            field=models.CharField(default='not available', max_length=200),
        ),
    ]
