# Generated by Django 2.2 on 2019-04-26 03:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20190426_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Location'),
        ),
    ]
