# Generated by Django 2.2 on 2019-04-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodelookup', '0002_auto_20190405_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_data',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default='https://i.ibb.co/dj1qb0D/product-image-not-found.gif'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
    ]
