# Generated by Django 2.2 on 2019-04-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodelookup', '0003_auto_20190408_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=40)),
                ('link', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='asin',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='barcodelookup.Product'),
        ),
    ]
