# Generated by Django 2.2 on 2019-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodelookup', '0004_auto_20190409_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asin',
            name='link',
        ),
        migrations.AddField(
            model_name='asin',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asin',
            name='image_url',
            field=models.TextField(default='https://i.ibb.co/dj1qb0D/product-image-not-found.gif'),
        ),
        migrations.AddField(
            model_name='asin',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asin',
            name='price',
            field=models.IntegerField(default=-1),
        ),
    ]
