# Generated by Django 2.2 on 2019-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodelookup', '0005_auto_20190424_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin',
            name='image_url',
            field=models.TextField(default='/media/images/product-image-not-found.gif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(default='/media/images/product-image-not-found.gif'),
        ),
    ]
