# Generated by Django 2.2 on 2019-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodelookup', '0006_auto_20190424_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='not available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
