# Generated by Django 2.2 on 2019-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodelookup', '0007_auto_20190424_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
